// This file has been generated by Specta. DO NOT EDIT.

export type CallsignDurationStats = { prefix: string; suffix: string; durationSeconds: number; isActive: boolean | null }

export type IronMicResponse = { requestedAt: string; lastDatafeedUpdatedAt: string; start: string; end: string; actualElapsedDurationSeconds: number; callsigns: CallsignDurationStats[] }

